# Generated by Django 4.2 on 2023-04-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_patient_id_diagnosis_patients_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnosis",
            old_name="patients_id",
            new_name="patient_id",
        ),
    ]
