# Generated by Django 4.2 on 2023-04-17 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_rename_patients_id_diagnosis_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
