# Generated by Django 4.2 on 2023-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_diagnosis_created_at_diagnosis_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mealplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.IntegerField()),
                ("doctor_id", models.IntegerField()),
                ("breakfast", models.CharField(max_length=500)),
                ("lunch", models.CharField(max_length=500)),
                ("dinner", models.CharField(max_length=500)),
                ("approved", models.BooleanField(default=False)),
            ],
        ),
    ]
