# Generated by Django 4.2 on 2023-04-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_mealplan_created_at_mealplan_diagnosis_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="bookinstance",
            name="book",
        ),
        migrations.RemoveField(
            model_name="bookinstance",
            name="borrower",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="BookInstance",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
