# Generated by Django 4.2 on 2023-05-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_book_author_remove_book_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="doctor_lastname",
            field=models.CharField(default="Dummy last name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="patient_lastname",
            field=models.CharField(default="Dummy last name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mealplan",
            name="doctor_lastname",
            field=models.CharField(default="Dummy last name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mealplan",
            name="patient_lastname",
            field=models.CharField(default="Dummy Last Name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mealplan",
            name="preference",
            field=models.CharField(default="None", max_length=500),
            preserve_default=False,
        ),
    ]
