# Generated by Django 4.2 on 2023-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_mealplan_allergy"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="description",
            field=models.CharField(
                default="Some diagnosis description", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
