# Generated by Django 4.2 on 2023-05-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_diagnosis_description_userprofile_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="patient", max_length=10),
            preserve_default=False,
        ),
    ]
