# Generated by Django 4.2 on 2023-05-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="checked_in_on",
            field=models.CharField(default="", max_length=100),
        ),
    ]
