DIAGNOSIS_CHOICES = [
    ("General consultation", "General consultation"),
    ("IBS", "IBS"),
    ("Fatty liver", "Fatty liver"),
    ("High blood pressure", "High blood pressure"), 
    ("PCOS", "PCOS"),
    ("Heart health", "Heart health"),
    ("Diabetes", "Diabetes"),
    ("Hypothyroidism", "Hypothyroidism"),
    ("Overweight/obesity", "Overweight/obesity"),
    ("High cholesterol", "High cholesterol"), 
    ("Hashimoto’s", "Hashimoto’s"),
    ("Menopause", "Menopause"),
    ( "Diverticulitis", "Diverticulitis"),
    ("Inflammation", "Inflammation"),
    ("Arthritis", "Arthritis"), 
    ("GERD", "GERD")
]

MEALPLAN_MAPPER = {
    'General consultation': {
        'breakfast': {"None": "Enter recommendations here!", 
                      "Vegetarian": "Enter recommendations here!",
                      "Vegan": "Enter recommendations here!",
                      "Pescatarian": "Enter recommendations here!"},
        'lunch': {"None": "Enter recommendations here!",
                      "Vegetarian": "Enter recommendations here!",
                      "Vegan": "Enter recommendations here!",
                      "Pescatarian": "Enter recommendations here!"},
        'dinner': {"None": "Enter recommendations here!",
                      "Vegetarian": "Enter recommendations here!",
                      "Vegan": "Enter recommendations here!",
                      "Pescatarian": "Enter recommendations here!"},
    },
    'IBS': {
        'breakfast': {"None": "Low FODMAP Blueberry Smoothie", 
                      "Vegetarian": "1 cup of low-fat Greek yogurt or plant-based yogurt alternative, 1 small bowl of low-fiber cereal like rice or corn flakes",
                      "Vegan": "1 small bowl of low-fiber oatmeal made with almond milk, 1 small serving of low-fodmap fruit like strawberries or blueberries",
                      "Pescatarian": "2 boiled eggs, 1 slice of whole-grain toast, 1 small serving of low-fodmap fruit like cantaloupe or grapes"
                      },
        'lunch': {"None": "Fresh Spring (Rice-Paper) Rolls. Select a maximum of 3 veggies (from this list) and add a protein if you like. Leave out avocado and scallions.",
                      "Vegetarian": "1 small bowl of roasted vegetable soup, 1 small whole-grain pita, 1 small side salad with mixed greens, carrots, and cucumbers",
                      "Vegan": "1 small bowl of low-fiber vegetable soup, 1 small serving of quinoa salad with low-fodmap vegetables like tomatoes, cucumbers, and carrots",
                      "Pescatarian": "1 small serving of tuna salad with low-fodmap vegetables like lettuce, cucumbers, and carrots, 1 small whole-grain pita, 1 small side salad with mixed greens and tomatoes"},
        'dinner': {"None": "Maple Garlic Glazed Salmon + low FODMAP veggies (see the link just above) + 1 cup cooked brown rice (for the fiber).",
                      "Vegetarian": "1 small serving of baked sweet potato, 1 small serving of tofu stir-fry with low-fodmap vegetables like bell peppers, carrots, and zucchini",
                      "Vegan": "1 small serving of baked sweet potato, 1 small serving of roasted chickpeas, 1 small side salad with mixed greens and tomatoes",
                      "Pescatarian": "1 small serving of baked salmon, 1 small serving of roasted low-fodmap vegetables like zucchini, bell peppers, and carrots, 1 small side salad with mixed greens and tomatoes"},
        },
    'Fatty liver': {
        'breakfast': {"None": "Utappam 2+ 1 tbs green chutney",
                      "Vegetarian": "2 boiled eggs or scrambled tofu, 1 slice of whole wheat toast, 1 small apple, 1 cup of green tea",
                      "Vegan": "1 bowl of oatmeal made with almond milk, 1 sliced banana, 1 tbsp of chia seeds, 1 cup of herbal tea",
                      "Pescatarian": "2 boiled eggs, 1 slice of whole-grain toast, 1 small fruit salad with mixed fruits like berries, apples, and kiwi, 1 cup of green tea"},
        'lunch': {"None": "1 cup rice+ Soya chunk curry1/2 cup+ Ladies finger subji 1/2 cup+ small cup low fat curd",
                      "Vegetarian": "1 small bowl of quinoa salad with mixed vegetables like bell peppers, tomatoes, onions, and cucumber",
                      "Vegan": "1 serving of baked tofu, 1 small bowl of brown rice, 1 small side salad with mixed greens, carrots, and cucumbers",
                      "Pescatarian": "1 small bowl of quinoa salad with mixed vegetables like bell peppers, tomatoes, onions, and cucumber, and a serving of grilled salmon"},
        'dinner': {"None": "Brocken wheat upma 1 cup+ 1/2 cup green beans subji",
                      "Vegetarian": "1 cup of lentil soup with vegetables like carrots, celery, and onions, 1 small baked sweet potato",
                      "Vegan": "1 cup of lentil soup with vegetables like carrots, celery, and onions, 1 small serving of roasted vegetables like broccoli",
                      "Pescatarian": "1 small serving of baked cod, 1 small baked sweet potato, 1 small side salad with mixed greens, avocado, and cherry tomatoes"},
        },
    'High blood pressure': {
        'breakfast': {"None": "1 store-bought (commercial) whole-wheat bagel with 2 tablespoons peanut butter (no salt added), 1 medium orange, 1 cup fat-free milk, decaffeinated coffee",
                      "Vegetarian": "1 small bowl of low-fat Greek yogurt or plant-based yogurt alternative, 1 small serving of fresh berries, 1 small slice of whole-grain toast with almond butter",
                      "Vegan": "1 small bowl of low-fat plant-based yogurt alternative, 1 small serving of fresh berries, 1 small slice of whole-grain toast with almond butter",
                      "Pescatarian": "1 small bowl of low-fat Greek yogurt, 1 small serving of fresh berries, 1 small slice of whole-grain toast with almond butter"},
        'lunch': {"None": "Spinach salad made with: 4 cups of fresh spinach leaves, 1 sliced pear, 1/2 cup canned mandarin orange sections, 1/3 cup slivered almonds, and 2 tablespoons red wine vinaigrette",
                      "Vegetarian": "1 small bowl of lentil soup with vegetables like carrots, celery, and onions, 1 small whole-grain pita, 1 small side salad with mixed greens, cucumbers, and tomatoes",
                      "Vegan": "1 small bowl of lentil soup with vegetables like carrots, celery, and onions, 1 small whole-grain pita, 1 small side salad with mixed greens, cucumbers, and tomatoes",
                      "Pescatarian": "1 small serving of tuna salad with low-fat mayo, mixed greens, cucumbers, and cherry tomatoes, 1 small whole-grain pita, 1 small side salad with mixed greens, cucumbers, and tomatoes"},
        'dinner': {"None": "Herb-crusted baked cod, 3 ounces cooked (about 4 ounces raw), 1/2 cup brown rice pilaf with vegetables, 1/2 cup fresh green beans - steamed, 1 small sourdough roll, 2 teaspoons olive oil, 1 cup fresh berries with chopped mint, and herbal iced tea",
                      "Vegetarian": "1 small serving of roasted eggplant, 1 small serving of quinoa with mixed vegetables like bell peppers, zucchini, and onions, 1 small side salad with mixed greens and cherry tomatoes",
                      "Vegan": "1 small serving of roasted eggplant, 1 small serving of quinoa with mixed vegetables like bell peppers, zucchini, and onions, 1 small side salad with mixed greens and cherry tomatoes",
                      "Pescatarian": "1 small serving of grilled salmon, 1 small serving of roasted low-sodium vegetables like asparagus, broccoli, and carrots, 1 small side salad with mixed greens and cherry tomatoes"},
        },
    'PCOS': {
        'breakfast': {"None": "1 cup ragi porridge +1 boiled egg",
                      "Vegetarian": "1 small bowl of low-fat Greek yogurt or plant-based yogurt alternative, 1 small serving of mixed berries, 1 small slice of whole-grain toast with avocado and tomato",
                      "Vegan": "1 small bowl of low-fat plant-based yogurt alternative, 1 small serving of mixed berries, 1 small slice of whole-grain toast with avocado and tomato",
                      "Pescatarian": "1 small bowl of low-fat Greek yogurt, 1 small serving of mixed berries, 1 small slice of whole-grain toast with avocado and tomato"},
        'lunch': {"None": "1 cup brown rice + 1 cup dal cooked with any green leafy vegetable + 1 cup vegetable curry",
                      "Vegetarian": "1 small bowl of lentil soup with mixed vegetables like carrots, celery, and onions, 1 small whole-grain pita, 1 small side salad with mixed greens, cucumbers, and cherry tomatoes",
                      "Vegan": "1 small bowl of lentil soup with mixed vegetables like carrots, celery, and onions, 1 small whole-grain pita, 1 small side salad with mixed greens, cucumbers, and cherry tomatoes",
                      "Pescatarian": "1 small serving of tuna salad with low-fat mayo, mixed greens, cucumbers, and cherry tomatoes, 1 small whole-grain pita, 1 small side salad with mixed greens, cucumbers, and cherry tomatoes"},
        'dinner': {"None": "Sautéed chicken with vegetables + buttermilk",
                      "Vegetarian": "1 small serving of grilled tofu, 1 small serving of quinoa with mixed vegetables like bell peppers, zucchini, and onions, 1 small side salad with mixed greens and cherry tomatoes",
                      "Vegan": "1 small serving of grilled tofu, 1 small serving of quinoa with mixed vegetables like bell peppers, zucchini, and onions, 1 small side salad with mixed greens and cherry tomatoes",
                      "Pescatarian": "1 small serving of grilled salmon, 1 small serving of quinoa with mixed vegetables like bell peppers, zucchini, and onions, 1 small side salad with mixed greens and cherry tomatoes"},
        },
    'Heart health': {
        'breakfast': {"None": "1 serving Avocado Egg Toast",
                      "Vegetarian": "1 cup cooked oatmeal with 1 sliced banana, 1 tablespoon chopped walnuts, and 1 teaspoon honey or maple syrup, 1 cup almond milk",
                      "Vegan": "1 cup cooked quinoa with 1 sliced pear, 1 tablespoon chopped almonds, and 1 teaspoon agave nectar or maple syrup, 1 cup soy milk",
                      "Pescatarian": ""},
        'lunch': {"None": "1 serving Loaded Black Bean Nacho Soup",
                      "Vegetarian": "Grilled vegetable wrap made with 1 whole wheat tortilla, grilled zucchini, eggplant, and red peppers, hummus, and mixed greens",
                      "Vegan": "Tofu stir-fry made with firm tofu, snow peas, bell peppers, and brown rice, 1 small kiwi, 1 cup unsweetened green tea",
                      "Pescatarian": ""},
        'dinner': {"None": "1 serving Seared Salmon with Green Peppercorn Sauce, 1 cup steamed green beans, 1 baked medium red potato, 1 Tbsp. nonfat plain Greek yogurt and a pinch of pepper.",
                      "Vegetarian": "Grilled portobello mushrooms with quinoa salad made with diced cucumbers, tomatoes, red onions, and lemon vinaigrette, steamed broccoli, 1 small orange",
                      "Vegan": "Vegan lentil soup made with lentils, diced tomatoes, carrots, and celery, whole grain dinner roll, mixed green salad with balsamic vinaigrette",
                      "Pescatarian": "Grilled salmon with roasted asparagus and brown rice, mixed green salad with balsamic vinaigrette, 1 small orange"},
        },
    'Diabetes': {
        'breakfast': {"None": "1 cup oatmeal, 1 tbsp sliced almonds, 1 tbsp ground flaxseed",
                      "Vegetarian": "1 cup cooked oatmeal with 1 sliced banana, 1 tablespoon chopped walnuts, and 1 teaspoon honey or maple syrup, 1 cup almond milk",
                      "Vegan": "1 cup cooked quinoa with 1 sliced pear, 1 tablespoon chopped almonds, and 1 teaspoon agave nectar or maple syrup, 1 cup soy milk",
                      "Pescatarian": "Smoked salmon and avocado toast made with 1 slice of whole grain bread, mashed avocado, smoked salmon, and sliced tomatoes, 1 cup green tea"},
        'lunch': {"None": "Turkey sandwich on, 2 slices whole wheat bread, raw veggies, hummus dip",
                      "Vegetarian": "Grilled vegetable wrap made with 1 whole wheat tortilla, grilled zucchini, eggplant, and red peppers, hummus, and mixed greens, 1 small apple",
                      "Vegan": "Tofu stir-fry made with firm tofu, snow peas, bell peppers, and brown rice, 1 small kiwi, 1 cup unsweetened green tea",
                      "Pescatarian": "Spinach and shrimp salad with a variety of vegetables (bell peppers, cucumbers, tomatoes) and a lemon vinaigrette, 1 small apple, 1 cup unsweetened iced tea"},
        'dinner': {"None": "3 oz grilled salmon, ½ cup baked potato, spinach salad, 1 cup skim milk",
                      "Vegetarian": "Grilled portobello mushrooms with quinoa salad made with diced cucumbers, tomatoes, red onions, and lemon vinaigrette, steamed broccoli",
                      "Vegan": "Vegan lentil soup made with lentils, diced tomatoes, carrots, and celery, whole grain dinner roll, mixed green salad with balsamic vinaigrette",
                      "Pescatarian": "Grilled salmon with roasted asparagus and brown rice, mixed green salad with balsamic vinaigrette, 1 small orange"},
        },
    'Hypothyroidism': {
        'breakfast': {"None": "Scrambled eggs with salmon",
                      "Vegetarian": "1 slice of whole-grain toast with 1 tablespoon of almond butter and sliced banana, 1 cup unsweetened almond milk",
                      "Vegan": "1 cup cooked oatmeal with 1/4 cup of unsweetened almond milk, 1/4 cup of fresh berries, and 1 tablespoon of ground flaxseed, 1 small apple, 1 cup unsweetened green tea",
                      "Pescatarian": "1 whole-grain English muffin with smoked salmon, avocado, and sliced tomato, 1 cup unsweetened green tea"},
        'lunch': {"None": "A salad with grilled shrimp",
                      "Vegetarian": "Lentil and vegetable soup made with lentils, carrots, celery, and spinach, 1 small orange, 1 cup unsweetened iced tea",
                      "Vegan": "Tofu and vegetable stir-fry with brown rice, 1 small pear, 1 cup unsweetened iced tea",
                      "Pescatarian": "Grilled shrimp and mixed greens salad with cucumbers, tomatoes, and a vinaigrette dressing, 1 small orange, 1 cup unsweetened iced tea"},
        'dinner': {"None": "A black bean and vegetable stir-fry with brown rice",
                      "Vegetarian": "Roasted portobello mushrooms stuffed with quinoa, diced vegetables (such as zucchini, tomatoes, and onions), and topped with shredded mozzarella cheese, steamed broccoli",
                      "Vegan": "Vegan lentil and vegetable curry served with brown rice, mixed green salad with balsamic vinaigrette, 1 small orange",
                      "Pescatarian": "Grilled salmon with roasted Brussels sprouts and sweet potatoes, mixed green salad with balsamic vinaigrette, 1 small apple"},
        },
    'Overweight/obesity': {
        'breakfast': {"None": "scrambled egg with spinach and tomato",
                      "Vegetarian": "2 hard-boiled eggs with a dash of hot sauce and salt",
                      "Vegan": "oatmeal with one-quarter cup of cooked rolled oats, a half cup of sliced banana, one-quarter cup of peanut butter, and soy or almond milk",
                      "Pescatarian": "Scrambled eggs with whole-grain toast and sliced avocado, and unsweetened green tea"},
        'lunch': {"None": "tuna salad with lettuce, cucumber, and tomato",
                      "Vegetarian": "kale salad with raisins, chickpeas, walnuts, and roasted sweet potatoes",
                      "Vegan": "Vegan lentil and vegetable soup with mixed green salad and balsamic vinaigrette, and small apple",
                      "Pescatarian": "grain bowl with 1 cup of quinoa and 1 cup of mixed vegetables including chick peas, Brussels sprouts, and broccoli"},
        'dinner': {"None": "bean chili with cauliflower ‘rice’",
                      "Vegetarian": "black bean burgers with avocado and roasted Brussels sprouts on the side",
                      "Vegan": "Grilled tofu with roasted sweet potatoes and Brussels sprouts, and small orange",
                      "Pescatarian": "sweet potato tacos with avocado, onion, and tomato"},
        },
    'High cholesterol': {
        'breakfast': {"None": "2–3 ounces (oz) smoked salmon with 1 tablespoon (tbsp) cream cheese, tomato slices",
                      "Vegetarian": "1/4 cup granola with 6 fluid ounces (fl oz) of Greek yogurt or vegan yogurt, 1/2 banana, 10 almonds, coffee or tea",
                      "Vegan": "1/4 cup granola with 6 fluid ounces (fl oz) of Greek yogurt or vegan yogurt, 1/2 banana, 10 almonds, coffee or tea",
                      "Pescatarian": "2 poached eggs with whole-grain toast and sliced avocado, and unsweetened green tea"},
        'lunch': {"None": "cooked skinless chicken breast with a mixed salad and vinaigrette, additional raw vegetables, water with lime slices",
                      "Vegetarian": "lentil soup, 1/2 sandwich with whole wheat bread and nut butter, small mixed green salad with vinaigrette, 1 cup fruit, water with lemon slices",
                      "Vegan": "lentil soup, 1/2 sandwich with whole wheat bread and nut butter, small mixed green salad with vinaigrette, 1 cup fruit, water with lemon slices",
                      "Pescatarian": "Grilled salmon and mixed greens salad with cucumbers, tomatoes, and vinaigrette, and small orange and unsweetened iced tea"},
        'dinner': {"None": "hamburger with no bun, grilled onions, mixed salad, 1 cup broccoli, water with lime",
                      "Vegetarian": "roasted cauliflower steak with spices, watermelon burrata salad, water with watermelon chunks",
                      "Vegan": "roasted cauliflower steak with spices, watermelon burrata salad, water with watermelon chunks",
                      "Pescatarian": "Grilled shrimp with mixed vegetables and quinoa, and small apple"},
        },
    'Hashimoto’s': {
        'breakfast': {"None": "Cherry berry smoothie bowl",
                      "Vegetarian": "Greek yogurt with mixed berries, almond butter, and cinnamon, and herbal tea",
                      "Vegan": " Chia pudding with mixed berries and almond milk, and herbal tea",
                      "Pescatarian": "Smoked salmon with whole-grain toast, avocado, and herbal tea"},
        'lunch': {"None": "Portable tuna pockets with fresh fruit",
                      "Vegetarian": "Lentil and vegetable soup with mixed greens salad and olive oil and lemon dressing, and small pear",
                      "Vegan": "Vegan lentil and vegetable soup with mixed greens salad and olive oil and lemon dressing, and small orange",
                      "Pescatarian": "Grilled salmon and mixed greens salad with cucumbers, tomatoes, and vinaigrette, and small orange"},
        'dinner': {"None": "Ultimate chopped salad",
                      "Vegetarian": "Grilled portobello mushrooms with mixed vegetables and quinoa, and small apple",
                      "Vegan": "Grilled tofu with mixed vegetables and brown rice, and small apple",
                      "Pescatarian": "Grilled shrimp with mixed vegetables and quinoa, and small apple"},
        },
    'Menopause': {
        'breakfast': {"None": "3-ingredient egg cups",
                      "Vegetarian": "Whole-grain cereal with mixed berries and almond milk, and herbal tea",
                      "Vegan": "Tofu and vegetable scramble with whole-grain toast, and herbal tea",
                      "Pescatarian": "2 scrambled eggs with whole-grain toast and sliced avocado, and herbal tea"},
        'lunch': {"None": "Roast beef with keto no-tato salad",
                      "Vegetarian": "Roasted vegetable and quinoa salad with mixed greens and vinaigrette, and small apple",
                      "Vegan": "Chickpea and vegetable stir-fry with brown rice and mixed green salad with vinaigrette, and small pear",
                      "Pescatarian": "Grilled shrimp and mixed greens salad with cucumbers, tomatoes, and vinaigrette, and small apple"},
        'dinner': {"None": "Baked chicken thighs with cauliflower rice and spinach dip",
                      "Vegetarian": "Grilled tofu with mixed vegetables and brown rice, and small orange",
                      "Vegan": "Grilled tempeh with mixed vegetables and quinoa, and small orange",
                      "Pescatarian": "Grilled salmon with mixed vegetables and brown rice, and small orange"},
        },
    'Diverticulitis': {
        'breakfast': {"None": "White bread Potato sandwich (2) + Milk (Toned)",
                      "Vegetarian": "Scrambled eggs with whole-grain toast, and herbal tea",
                      "Vegan": "Tofu and vegetable scramble with whole-grain toast, and herbal tea",
                      "Pescatarian": "Smoked salmon with whole-grain toast and sliced avocado, and herbal tea"},
        'lunch': {"None": "Maida Roti (2) + Soy bean Curry (1/2 cup)",
                      "Vegetarian": "Roasted vegetable and lentil soup with mixed greens salad and olive oil and lemon dressing, and small pear",
                      "Vegan": "Vegan lentil and vegetable soup with mixed greens salad and olive oil and lemon dressing, and small orange",
                      "Pescatarian": "Grilled shrimp and mixed greens salad with cucumbers, tomatoes, and vinaigrette, and small apple"},
        'dinner': {"None": "Maida Roti (1) + Bottle Gourd Curry (1/2 cup)",
                      "Vegetarian": "Grilled portobello mushrooms with mixed vegetables and quinoa, and small apple",
                      "Vegan": "Grilled tempeh with mixed vegetables and brown rice, and small apple",
                      "Pescatarian": "Grilled salmon with mixed vegetables and quinoa, and small orange"},
        },
    'Inflammation': {
        'breakfast': {"None": "1 serving Blueberry-Banana Overnight Oats, and 1 cup green tea",
                      "Vegetarian": "Whole-grain oatmeal with mixed berries and walnuts, and herbal tea",
                      "Vegan": "Chia pudding with mixed berries and almond milk, and herbal tea",
                      "Pescatarian": "Smoked salmon with whole-grain toast, avocado, and herbal tea"},
        'lunch': {"None": "1 serving Green Salad with Edamame & Beets",
                      "Vegetarian": "Roasted vegetable and quinoa salad with mixed greens and vinaigrette, and small apple",
                      "Vegan": "Chickpea and vegetable stir-fry with brown rice and mixed green salad with vinaigrette, and small pear",
                      "Pescatarian": "Grilled shrimp and mixed greens salad with cucumbers, tomatoes, and vinaigrette, and small orange"},
        'dinner': {"None": "1 serving Walnut-Rosemary Crusted Salmon, 1 serving Roasted Squash & Apples with Dried Cherries & Pepitas",
                      "Vegetarian": "Grilled portobello mushrooms with mixed vegetables and brown rice, and small orange",
                      "Vegan": "Grilled tempeh with mixed vegetables and quinoa, and small apple",
                      "Pescatarian": "Grilled salmon with mixed vegetables and brown rice, and small apple"},
        },
    'Arthritis': {
        'breakfast': {"None": "1 serving Blueberry-Banana Overnight Oats, and 1 cup green tea",
                      "Vegetarian": "Greek yogurt with mixed berries and granola, and herbal tea",
                      "Vegan": "Smoothie with mixed berries, banana, spinach, and almond milk, and herbal tea",
                      "Pescatarian": "Smoked salmon with whole-grain toast, avocado, and herbal tea"},
        'lunch': {"None": "1 serving Green Salad with Edamame & Beets",
                      "Vegetarian": "Quinoa and lentil salad with mixed greens and vinaigrette, and small apple",
                      "Vegan": "Roasted sweet potato and black bean bowl with mixed greens and vinaigrette, and small pear",
                      "Pescatarian": "Grilled shrimp and mixed greens salad with cucumbers, tomatoes, and vinaigrette, and small orange"},
        'dinner': {"None": "1 serving Walnut-Rosemary Crusted Salmon, 1 serving Roasted Squash & Apples with Dried Cherries & Pepitas",
                      "Vegetarian": "Grilled tofu with mixed vegetables and brown rice, and small orange",
                      "Vegan": "Grilled tempeh with mixed vegetables and quinoa, and small apple",
                      "Pescatarian": "Grilled salmon with mixed vegetables and brown rice, and small apple"},
        },
    'GERD': {
        'breakfast': {"None": "Low-fat yoghurt with melon and apple",
                      "Vegetarian": "Greek yogurt with sliced banana and granola, and herbal tea",
                      "Vegan": "Smoothie with spinach, banana, almond milk, and chia seeds, and herbal tea",
                      "Pescatarian": "Scrambled eggs with whole-grain toast and herbal tea"},
        'lunch': {"None": "Turkey in a whole-grain wrap with spinach and low-fat hummus",
                      "Vegetarian": "Quinoa and roasted vegetable bowl with mixed greens and vinaigrette, and small apple",
                      "Vegan": "Chickpea and vegetable stir-fry with brown rice and mixed green salad with vinaigrette, and small pear",
                      "Pescatarian": "Grilled shrimp and mixed greens salad with cucumbers, tomatoes, and vinaigrette, and small orange"},
        'dinner': {"None": "Poached salmon with brown quinio and courgette",
                      "Vegetarian": "Grilled tofu with mixed vegetables and brown rice, and small orange",
                      "Vegan": "Grilled tempeh with mixed vegetables and quinoa, and small apple",
                      "Pescatarian": " Grilled salmon with mixed vegetables and brown rice, and small apple"},
        },
}
