DIAGNOSIS_CHOICES = [
    ("IBS", "IBS"),
    ("Fatty liver", "Fatty liver"),
    ("High blood pressure", "High blood pressure"), 
    ("PCOS", "PCOS"),
    ("Heart health", "Heart health"),
    ("Diabetes", "Diabetes"),
    ("Hypothyroidism", "Hypothyroidism"),
    ("Overweight/obesity", "Overweight/obesity"),
    ("High cholesterol", "High cholesterol"), 
    ("Hashimoto’s", "Hashimoto’s"),
    ("Menopause", "Menopause"),
    ( "Diverticulitis", "Diverticulitis"),
    ("Inflammation", "Inflammation"),
    ("Arthritis", "Arthritis"), 
    ("GERD", "GERD")
]

MEALPLAN_MAPPER = {
    'IBS': {
        'breakfast': {"None": "Low FODMAP Blueberry Smoothie", 
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Fresh Spring (Rice-Paper) Rolls. Select a maximum of 3 veggies (from this list) and add a protein if you like. Leave out avocado and scallions.",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Maple Garlic Glazed Salmon + low FODMAP veggies (see the link just above) + 1 cup cooked brown rice (for the fiber).",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Fatty liver': {
        'breakfast': {"None": "Oatmeal (with added chia seeds, berries, or fruits of choice)",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Grilled chicken or fish with cooked veggies (broccoli, carrot, beans, etc. can be added) or Any lentil curry with steamed rice or Oats atta roti",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Mixed bean salad along with 1 cup of cooked quinoa or fish or a big bowl of seasonal vegetable cooked.",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'High blood pressure': {
        'breakfast': {"None": "1 cup of fresh mixed fruits, 1 cup of fat-free, low-calorie vanilla-flavored yogurt, 1/3 cup walnuts, 1 bran muffin, 1 teaspoon trans-free margarine",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Curried chicken wrap w/ 2/3 cup cooked, chopped chicken, about 3 ounces; 1/2 cup, or about 8, raw baby carrots, and 1 cup fat-free milk",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "1 cup cooked whole-wheat spaghetti with 1 cup marinara sauce, 2 cups mixed salad greens, 1 tablespoon low-fat Caesar dressing",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'PCOS': {
        'breakfast': {"None": "Banana Yogurt Pots: 225g / ⅞ cup Greek yogurt, 225g / ⅞ cup Greek yogurt, 15g / 2 tbsp walnuts, toasted and chopped",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Cannellini Bean Salad, 600g / 3 cups cannellini beans, 70g / ⅜ cup cherry tomatoes, halved, ½ red onion, thinly sliced, ½ tbsp red wine vinegar, small bunch basil, torn",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Quick Moussaka",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Heart health': {
        'breakfast': {"None": "1 serving Avocado Egg Toast",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "1 serving Loaded Black Bean Nacho Soup",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "1 serving Seared Salmon with Green Peppercorn Sauce, 1 cup steamed green beans, 1 baked medium red potato, 1 Tbsp. nonfat plain Greek yogurt and a pinch of pepper.",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Diabetes': {
        'breakfast': {"None": "1 cup low-fat plain Greek yogurt, ¼ cup blueberries, 3 Tbsp. chopped walnuts",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "1 serving White Bean & Veggie Salad",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "1 serving Garlic Butter-Roasted Salmon with Potatoes & Asparagus",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Hypothyroidism': {
        'breakfast': {"None": "Cherry berry smoothie bowl",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Portable tuna pockets with fresh fruit",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Ultimate chopped salad",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Overweight/obesity': {
        'breakfast': {"None": "Banana Yogurt Pots: 225g / ⅞ cup Greek yogurt, 225g / ⅞ cup Greek yogurt, 15g / 2 tbsp walnuts, toasted and chopped",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Cannellini Bean Salad, 600g / 3 cups cannellini beans, 70g / ⅜ cup cherry tomatoes, halved, ½ red onion, thinly sliced, ½ tbsp red wine vinegar, small bunch basil, torn",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Quick Moussaka",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'High cholesterol': {
        'breakfast': {"None": "Banana Yogurt Pots: 225g / ⅞ cup Greek yogurt, 225g / ⅞ cup Greek yogurt, 15g / 2 tbsp walnuts, toasted and chopped",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Cannellini Bean Salad, 600g / 3 cups cannellini beans, 70g / ⅜ cup cherry tomatoes, halved, ½ red onion, thinly sliced, ½ tbsp red wine vinegar, small bunch basil, torn",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Quick Moussaka",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Hashimoto’s': {
        'breakfast': {"None": "Cherry berry smoothie bowl",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Portable tuna pockets with fresh fruit",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Ultimate chopped salad",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Menopause': {
        'breakfast': {"None": "3-ingredient egg cups",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Roast beef with keto no-tato salad",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Baked chicken thighs with cauliflower rice and spinach dip",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Diverticulitis': {
        'breakfast': {"None": "White bread Potato sandwich (2) + Milk (Toned)",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Maida Roti (2) + Soy bean Curry (1/2 cup)",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Maida Roti (1) + Bottle Gourd Curry (1/2 cup)",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Inflammation': {
        'breakfast': {"None": "1 serving Blueberry-Banana Overnight Oats, and 1 cup green tea",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "1 serving Green Salad with Edamame & Beets",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "1 serving Walnut-Rosemary Crusted Salmon, 1 serving Roasted Squash & Apples with Dried Cherries & Pepitas",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'Arthritis': {
        'breakfast': {"None": "1 serving Blueberry-Banana Overnight Oats, and 1 cup green tea",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "1 serving Green Salad with Edamame & Beets",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "1 serving Walnut-Rosemary Crusted Salmon, 1 serving Roasted Squash & Apples with Dried Cherries & Pepitas",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
    'GERD': {
        'breakfast': {"None": "Low-fat yoghurt with melon and apple",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'lunch': {"None": "Turkey in a whole-grain wrap with spinach and low-fat hummus",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        'dinner': {"None": "Poached salmon with brown quinio and courgette",
                      "Vegetarian": "",
                      "Vegan": "",
                      "Pescatarian": ""},
        },
}
